### ISSUE TITLE
[Feature Request] Add support for youtube StreamLabs events

### ISSUE THREAD

**Issue by bluefutureMC** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#18]
Hi, I tried to connect my streamlabs to this mod because I want to stream my modpack on youtube.
I tested it and discovered that it only supports twitch stream events.
Is it possible to also add youtube events support like super chat and new subscriber?

**Comment by MeinKraft** [comment]
I have the same problem with StreamElements not detecting YT events. Please support  YT on StreamElements too

**Comment by iChun** [comment]
Oh uhm. I just realised that I'm going to need to have a look at the logs
that CCI makes. Because it may contain sensitive information, I suggest you
email it directly to me ohai.iChun@gmail.com

I'm filtering most of streamlabs and StreamElements events through CCI
anyway so it's possible that it is on their end where its not supported.
I'll have to look through the CCI logs to find out.

**Comment by iChun** [comment]
Anyways since there was no reply: Check out here for info on streamlabs' socket api use, which includes twitch, mixer, youtube, etc. https://dev.streamlabs.com/docs/socket-api

Streamlab and StreamElement events do get printed to the log.
