### ISSUE TITLE
Eliminate the need for server side installation

### ISSUE THREAD

**Issue by Qeelin** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#40]
Is there a way to eliminate the need to install CCI on a server and only run it client side? This would make it possible to use it on vanilla servers or servers that we don't have the ability to add mods to (provided we have op rights).

**Comment by iChun** [comment]
Thanks for making this issue for me. I meant it more specifically for Command Outcome. CCI on it's own works client-only anyway, server-side installation generally isn't required. There's a list of Outcomes which will work without a server but because the mod lacks documentation a lot of them are not known.

**Comment by iChun** [comment]
For those of you reading this out of curiosity/you have similar requests: 

CCI has never been required on a server. It was built from the ground up with the intent of not needing a server. The issue is most of the outcomes require a serverside connection to do the magic, especially stuff like CommandOutcome. Internally CCI checks with the outcome if it can be triggered on the client or not, like ToastOutcome, NarratorOutcome, etc. 

This issue in particular which I asked Qeelin to make is to address CommandOutcome also requiring the server to have CCI installed, because I didn't think at the time that it could be a client outcome by, basically, sending a chat message with the command, like normal vanilla does. Doing it that way will allow CCI to work on servers that don't have CCI installed, as long as the player has the right permissions to trigger the commands they want to. That fallback function should now be in v1.2.4, whenever released.
