### ISSUE TITLE
Streamelements don't work

### ISSUE THREAD

**Issue by pepijnno** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#59]
When I enter my streamelements code I don't get a follower message when I test it en I get 5 times subscriber message when I test it

**Comment by iChun** [comment]
Do you still need assistance with this issue?

**Comment by MeinKraft** [comment]
Im not sure about this guys issue, but I can confirm when using the "Emulate" button on my StreamElements page to test my rewards, they do activate at least 6 times each, in this instance I get 6 messages on screen when I should only get 1

I was using a simple Cheer test with a RangeAmountCondition and CommandOutcome.
The CommandOutcome was /tellraw @s "Hello"

**Comment by iChun** [comment]
The last time I did some test events, the event isn't actually triggered 6 times, but they're actually 6 different kinds of events. Unfortunately StreamElements (and the same for Streamlabs) test events don't really match real/actual events, and the defaults are supposed to be compatible with the real events rather than test events.

Unless this is an actual issue where real events aren't triggering for StreamElements I'm afraid there's not much I can do about this, without logs or any other info.
