### ISSUE TITLE
1.21 Support 

### ISSUE THREAD

**Issue by Allybe** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#97]

**Comment by iChun** [comment]
I'm aware 1.21 is out. These kinds of issues do not help

**Comment by Allybe** [comment]
I apologize, this issue was meant more as a track of progress of this issue, rather than being a push to make you do it. Thought it'd be useful to those looking to see if you are aware of the issue.

**Comment by iChun** [comment]
Fair enough, but around I reckon prolly in the mod-dev scene, these kind of issues would be more of a request rather than a tracker for progress - especially since the issue wasn't created by anyone on the dev team. 

I'm still in the progress of working on 1.20.6 stuffs. An update to 1.21 will be out when it's done
